Change time to harris_time to not clash with system symbol
    ./types.h:40:1: error: redefinition of 'time' as different kind of symbol
    time;
    ^
    /usr/include/time.h:154:8: note: previous definition is here
    time_t time(time_t *);
           ^